### ISSUE TITLE
Read Data Documentation

### ISSUE THREAD

**Issue by ajhaller** [sds-capstone/2022-09-proj7-women-at-table#10]

**Comment by rporta23** [comment]
Gebru, Timnit, Jamie Morgenstern, Briana Vecchione, Jennifer Wortman Vaughan, Hanna Wallach, Hal Daumé III, and Kate Crawford. ‘Datasheets for datasets’. arXiv:1803.09010 [cs], 19 Μάρτιος 2020. http://arxiv.org/abs/1803.09010 .

**Comment by MargaretBassney** [comment]
**Data Documentation Notes**

**Need to understand the context of the data and its potential biases**
- Machine learning models reflect or exaggerate the biases in the data set.
- Models won't perform well in a context that is outside the scope of the training data.
- To help data set creators and data set users, a standardized documentation method must be created

 **Data sheet for Data set must include**
Questions are grouped into categories that reflect the dataset workflow
Not all questions may be possible to answer but its important to try and answer most of them

_I won't include all the questions that were in the article in my notes, this article seems more like a good document to reference when needed_

**- motivation: who/what/where/when/why questions**

"For what purpose was the dataset created? Was there a specific task in mind? Was there a specific gap that needed to be filled? Please provide a description"


- **composition:** Data collectors should read through questions before they start collectinginformation about the data itself. what is in the data. how many observations are there. Is there noise in the data, is the data unprocessed?

"Does the dataset contain all possible instances or is it a sample (not necessarily random) of instances from a larger set? If the dataset is a sample, then what is the larger set? Is the sample representa- tive of the larger set (e.g., geographic coverage)? If so, please describe how this representativeness was validated/verified. If it is not representative of the larger set, please describe why not (e.g., to cover a more diverse range of instances, because instances were withheld or unavailable)"


- **collection process:** Data collectors should read through questions before they start collecting.

"Who was involved in the data collection process (e.g., students, crowdworkers, contractors) and how were they compensated (e.g., how much were crowdworkers paid)?"


"Over what timeframe was the data collected?"



- **Preprocessing/Cleaning/Labelling:** has the data been processed in a way that will make it unsuitable for certain tasks


"Was any preprocessing/cleaning/labeling of the data done (e.g., discretization or bucketing, tokenization, part-of-speech tagging, SIFT feature extraction, removal of instances, processing of miss- ing values)?"


- **Uses:** what should the data be used for/what shouldn't it be used for

"Is there anything about the composition of the dataset or the way it was collected and preprocessed/cleaned/labeled that might impact future uses?"




**-Distribution**

"How will the dataset will be distributed (e.g., tarball on website, API, GitHub)? Does the dataset have a digital object identifier (DOI)?"

" When will the dataset be distributed?"

**Reason**

-" increase transparency and accountability within the machine learning community"

no underlying biases in the data should be hidden. Data set consumers should know exactly what they are getting with the data they are using. This way they know they are using the right data set for their project. 

-  "mitigate unwanted societal biases in machine learning models"

Proper documentation could prevent misuse of the data set and protect individuals who could be impacted by the models created. 

-  "facilitate greater reproducibility of machine learning results"

Other data scientists should be able to look at the documentation and be able to produce a similar data set.

- "help researchers and practitioners to select more appropriate datasets for their chosen tasks"

**Comment by rporta23** [comment]
read-- noticing that many of the questions in the "questions to ask" sections of the Jupyter notebook are pulled from this paper, so this could be a useful reference if we need more clarification on those.

**Comment by ajhaller** [comment]
Read

**Comment by alejanmg** [comment]
read
