### ISSUE TITLE
First draft Introduction

### ISSUE THREAD

**Issue by MargaretBassney** [sds-capstone/2022-09-proj7-women-at-table#24]
write a complete introductory section. This section should be complete and include a compreshensible description of your problem, and why the previous approaches to solving it were insufficient

**Comment by rporta23** [comment]
Looks great to me! Just a couple of small notes:
* For now say that we are focusing on gender only instead of gender, age, and race. Our dataset does not include race, so there is no way we can focus on that. We may focus on age later on, but I think gender is our primary focus for now.
* You might consider breaking it into two paragraphs-- the one paragraph is pretty long.
* Generally formal writing doesn't use contractions (eg use are not rather than aren't)
* Very nit-picky thing, but make sure there is a space between the period and the first letter of the following sentence for all sentences-- there are a few sentences where there is not.

**Comment by MargaretBassney** [comment]
Thank you! I just made these changes and pushed the file so I'll move this part to done then. Thanks for the tip about contractions! I'm so lazy about those things lol
